# Site settings
title: Sky is the limit
about: Web developer at Yandex, runner
email: zumra6a@yandex.ru
description: >
  This is systematized archive of my thoughts.
  Don't be scared if you find posts in Russian or in Turkish.
  Please feel free to correct my mistakes.

baseurl: ""
url: "http://shuhrat.github.io"
timezone: Europe/Moscow

# Conversion
markdown: kramdown
markdown_ext: markdown,md
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
highlighter: rouge

encoding: UTF-8

# Outputting
paginate: 6
permalink: "/:categories/:title.html"
paginate_path: "/page/:num"

# Contacts
contacts:
  twitter: zumra6a
  instagram: zumra6a
  github:  shuhrat

metrika:
  id: 28307931
  webvisor: true
  clickmap: true
  trackLinks: true

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true

gems:
  - jemoji
  - jekyll-gist
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
